"""add user relationship

Revision ID: e38fa223f58e
Revises: e7b262224b03
Create Date: 2025-10-23 23:19:57.722521

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e38fa223f58e"
down_revision: Union[str, Sequence[str], None] = "e7b262224b03"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("todos", schema=None) as batch_op:
        batch_op.add_column(sa.Column("user_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key("fk_todos_user_id", "users", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("todos", schema=None) as batch_op:
        batch_op.drop_constraint("fk_todos_user_id", type_="foreignkey")
        batch_op.drop_column("user_id")
    # ### end Alembic commands ###
